apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gemma-system

resources:
  - namespace.yaml
  - pvcs.yaml
  - gemma-1b-deployment.yaml
  - gemma-9b-deployment.yaml
  - gemma-27b-deployment.yaml

labels:
  - pairs:
      demo: argo-rollouts
