apiVersion: v1
kind: Service
metadata:
  name: gemma-server
  namespace: gemma-system
  labels:
    app: gemma-server
    demo: argo-rollouts
spec:
  selector:
    app: gemma-server
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
